name: EV-${project.name}
version: ${plugin.version}
description: ${project.description}

main: fr.ethilvan.bukkit.${project.artifactId}.${project.name}Plugin
depend: [EV-API]

commands:
    evmisc:
        description: "Commande principale."
        usage: "book"
        aliases: ["misc"]

     # Livre
    "evmisc book":
        description: "Commande pour les livres"
        usage: "<author|title|pages|page>"
        aliases: ["book"]
    "evmisc book author":
        description: "Redéfinis l'auteur"
        usage: "<author>"
        aliases: ["author"]
        permission: "ev.misc.commands.book.author"
    "evmisc book pages":
        description: "Redéfinis les pages"
        usage: "<pages...>"
        aliases: ["pages"]
        permission: "ev.misc.commands.book.pages"
    "evmisc book page":
        description: "Redéfinis une page"
        usage: "[page] [data]"
        aliases: ["page"]
        permission: "ev.misc.commands.book.page"
    "evmisc book title":
        description: "Redéfinis le titre du livre"
        usage: "<title>"
        aliases: ["title"]
        permission: "ev.misc.commands.book.title"

permissions:

    "ev.misc.commands.book.*":
        children:
            ev.misc.commands.book.author: true
            ev.misc.commands.book.pages: true
            ev.misc.commands.book.page: true
            ev.misc.commands.book.title: true